import type { Metadata } from "next";
import { Pathway_Gothic_One } from "next/font/google";
import "./globals.css";

const PathwayGoth = Pathway_Gothic_One({weight: '400', subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PathwayGoth.className}>{children}</body>
    </html>
  );
}
